import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        flexDirection:"column",
        width:"100%",     
        alignItems:"center"
    },
    FlatlistStyle:{
        width:"100%",
        alignItems:"center"
    },
    FlatTitleStyle:{
        width:"100%",
        margin:10
    },
    FlatTitleStyleText:{
        fontWeight:"600",
        fontSize:20,
        margin:5,
        marginTop:20,
        marginLeft:20
    },  
    DetBox:{
        borderWidth:1,
        width:"90%",
        flexDirection:"row",
        alignItems:"center",
        margin:6,
        padding:10,
        borderRadius:10,
        backgroundColor:"lightgray",
        borderColor:"gray"
    },
    DetBoxSoon:{
        opacity:0.3,
        borderWidth:1,
        width:"90%",
        flexDirection:"row",
        alignItems:"center",
        margin:6,
        padding:10,
        borderRadius:10,
        backgroundColor:"lightgray",
        borderColor:"gray"
    },
    assistantTitle:{
        flexDirection:'column',
        justifyContent:'center',
        padding:20,
        width:'100%',
        borderWidth:0,
    },
    assistantQuestionsContainer:{
        flexDirection:'row',
        flexWrap:'wrap',
        width:'100%',
        maxWidth:'100%',
        marginTop:0,
        justifyContent:'center',
        alignItems:'center',
        borderWidth:0,
    },
    assistantQuestionBox:{
        width:150,
        height:0,
        borderWidth:1,
        margin:10,
        borderRadius:1,
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        padding:10,
        opacity:0.6,
    },
    inputContainerNotActive:{
        width:'100%',
        flexDirection:'row',
        padding:20,
        borderWidth:0,
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        bottom:0,
        zIndex:5,
    },
    inputContainerActive:{
        width:'100%',
        padding:20,
        borderWidth:1,
        alignItems:'flex-start',
        justifyContent:'center',
        position:'absolute',
        bottom:0,
        backgroundColor:'white',
        flexDirection:'row',
        height:"60%"
    },
    inputField:{
        width:'80%',
        height:50,
        borderWidth:1,
        borderRadius:5,
        padding:10,
        zIndex:5,
    },
    horizontalQuBox:{
        backgroundColor:'black',
        borderRadius:5,
        height:60,
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'column',
        marginTop:30,
        marginBottom:10,
        opacity:1,
        width:"80%"
    },
    contextBox:{
        height:160,
        width:"90%",
        marginTop:40,
        borderRadius:20,
        flexDirection:"row",
        alignItems:"flex-end",
        justifyContent:"center"
    },
    cardRight:{
        width:"72%",
        height:"90%",
        borderRightWidth:10,
        backgroundColor:"black",
        borderRadius:10,
        borderTopRightRadius:0,
        borderTopLeftRadius:0,
        borderBottomRightRadius:0,
        padding:20,
        justifyContent:"space-between"
    },
    cardLeft:{
        padding:8,
        alignItems:"center",
        width:"28%",
        height:"100%",
        borderTopLeftRadius:20,
        borderTopRightRadius:15,
        borderBottomRightRadius:10,
        backgroundColor:"black"
    },
    searchInputContainer:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:2,
        width:"80%",
        marginTop:70,
        borderRadius:10,
        padding:10,
        justifyContent:"center",
    },
    searchInput:{
        borderWidth:0,
        width:"70%",
        marginLeft:20,
    },
    addInputContainer:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:1,
        width:"80%",
        marginTop:30,
        borderRadius:50,
        padding:12,
        backgroundColor:"black",
        justifyContent:"center",
        borderColor:"white"
    },
    addInputContainerMental:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:1,
        width:"80%",
        marginTop:20,
        borderRadius:50,
        padding:12,
        backgroundColor:"white",
        justifyContent:"center"        
    },
    loadingModal:{
        alignItems:"center",
        justifyContent:"center",
        position:"absolute",
        width:"100%",
        height:"100%",
        backgroundColor: "rgba(0, 0, 0, 0)",
        paddingBottom:200
    },
    IndicatorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',        
        backgroundColor:"rgba(0,0,0,1)",
        padding:15,    
        borderBottomLeftRadius:30,        
        borderBottomRightRadius:30,        
        marginBottom:0,
        marginTop:0,
        width:"50%",
        alignSelf:"center"
    },
    Indicator: {
        width: 6,
        height: 6,
        backgroundColor: 'white',
        borderRadius: 3,
        marginHorizontal: 5,
    },
});


export const ExpStyle = StyleSheet.create({
    container:{
        width:"100%",
        height:"100%",
        backgroundColor:"white",
        paddingTop:100,
        alignItems:"center",
        
    },
    section:{
        width:"100%",
        padding:0,
        maxWidth:"100%",
        borderWidth:0,
        flexWrap:"wrap",
        alignItems:"center",
        flexDirection:"row",
        justifyContent:"center",
        paddingBottom:20,
        borderBottomWidth:0.3
    },
    featureBox:{
        width:"90%",
        height:170,
        borderWidth:3,
        borderColor:"white",
        borderRadius:10,
        margin:10,
        flexDirection:"column",
        justifyContent:"space-between",
        padding:0,
        alignItems:"center",
        backgroundColor:"black"
    }
})
