version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/serviceAccountKey.json"
