[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
rocket = "0.5.1"
rocket_codegen = "0.5.1"
rocket_sync = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
